apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  restaurantdb: restaurantdb
  mysql-server: mysql-service    
  mysql-user-username: root
  foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-service:3306/userdb
  foodcataloguedb: foodcataloguedb
  userdb: userdb